version: '3.4'

services:
  simpleudpreflector:
    image: simpleudpreflector
    build:
      context: SimpleUDPReflector
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 40000:40000
